### ISSUE TITLE
What should I write if I don't have a password?

### ISSUE THREAD

**Issue by OluOrojo** [MIT-LCP/bhi-bsn-challenge#9]
I don't have a password on my database and get the error below:
psycopg2.OperationalError: fe_sendauth: no password supplied

For password what can I put,below I didn't write any password.
Create a database connection
user = 'postgress'
password = ''
host = 'localhost'
dbname = 'mimic'
schema = 'mimic'

**Comment by tompollard** [comment]
The challenge is now over, and we aren't able to provide general support for this repository. I would suggest searching the web for the error.

The issue is that you need to set up a database connection from Python to your postgres database (note the 'postgres' typo in your posting, though I'm not sure if this issue is related).
